core/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

odonto/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),    
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('account/', include('account.urls')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path
from . import views

# Create your views here.

app_name = 'quiz'
urlpatterns = [
    path('forms/', views.forms, name='forms')
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    template_name = 'home.html'
    return render(request, template_name)

core/templates/home.html
{% extends "base/base.html" %}
{% load static %}

{% block titulo %} Pagina Principal {% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/core/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/core/home.css' %}">
{% endblock %}

{% block conteudo %}
<div class="container">
    <div class="container-welcome">
        <div class="welcome">
            <span>BEM-VINDO</span>
            <span class="name">Olá, {{ user.first_name }} {{ user.last_name }}!</span>
        </div>
    </div>

    <div class="container-fast-action">
        <div class="box-action-txt">
            <div class="action-txt">
                <p>Ações rápidas</p>
            </div>
        </div>
        <div class="box-fast-action">
            <div class="fast-action">
                <div class="item">
                    <img src="{% static 'img/icons/journal-medical.svg'%}" />
                </div>
                <p>Histórico de Consulta</p>
                <!-- <p>Clientes</p> -->
            </div>
            <div class="fast-action">
                <div class="item">
                    <img src="{% static 'img/icons/last-appointment.svg'%}" />
                </div>
                <p>Última Consulta</p>
            </div>
            <div class="fast-action">
                <div class="item">
                    <img src="{% static 'img/icons/user.svg'%}" />
                </div>
                <p>Meu Perfil</p>
            </div>
            <div class="fast-action">
                <a href="{% url 'quiz:forms' %}"></a>
                <div class="item">
                    <img src="{% static 'img/icons/card-checklist.svg'%}" />
                </div>
                </a>
                <p>Anamnese</p>

            </div>
            <div class="fast-action">
                <a href="{% url 'quiz:forms' %}">
                    <div class="item">
                        <img src="{% static 'img/icons/calendar-event.svg'%}" />
                    </div>
                </a>
                <p>Agendar Consulta</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}